apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-rollouts

helmCharts:
  - name: argo-rollouts
    namespace: argo-rollouts
    releaseName: argo-rollouts
    repo: https://argoproj.github.io/argo-helm
    valuesFile: config/values.yaml
    version: 2.39.5

resources:
  - resources/namespace.yaml
