apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: argo-rollouts
  namespace: argo-cd

spec:
  project: argo-cd
  source:
    repoURL: git://k8sage/argo-rollouts/
    targetRevision: HEAD
    path: .
  destination:
    name: in-cluster
    namespace: argo-rollouts
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
      - Validate=false
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
