apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-cd

resources:
  - config/namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - https://raw.githubusercontent.com/argoproj-labs/rollout-extension/v0.3.1/manifests/install.yaml
  - secrets/repocreds.yaml
  - ../../components/applicationsets
  - ../../components/projects

components:
  - https://github.com/argoproj-labs/argocd-extensions/manifests

configurations:
  - config/rbac.yaml

transformers:
  - transformers/namespace-transformer.yaml

patches:
  - path: patches/config.patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
  - path: patches/password.patch.yaml
    target:
      kind: Secret
      name: argocd-secret
  - path: patches/server.patch.yaml
    target:
      kind: Service
      name: argocd-server
