apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: applications
  namespace: argo-cd

spec:
  description: Applications infrastructure project
  sourceRepos:
    - 'git://host.k3d.internal/applications/*/'
  destinations:
    - namespace: '!default'
      server: '*'
    - namespace: '!kube-*'
      server: '*'
    - namespace: '!argo-cd'
      server: '*'
    - namespace: '!argo-rollouts'
      server: '*'
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
