apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: apps
  namespace: argo-cd

spec:
  description: Apps infrastructure project
  sourceRepos:
    - '!git://host.k3d.internal/k8sage/'
    - '*'
  destinations:
    - namespace: '!default'
      server: '*'
    - namespace: '!kube-*'
      server: '*'
    - namespace: '!argo-cd'
      server: '*'
    - namespace: '!argo-rollouts'
      server: '*'
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
