apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: core
  namespace: argo-cd

spec:
  description: Core infrastructure project
  sourceRepos:
    - git://host.k3d.internal/k8sage/
  destinations:
    - namespace: argo-cd
      server: '*'
    - namespace: argo-rollouts
      server: '*'
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
