nameOverride: ""

configs:
  cm:
    kustomize.buildOptions: "--enable-helm --enable-alpha-plugins"
  params:
    server.basehref: /argo-cd
    server.disable.auth: true
    server.insecure: true
  secret:
    argocdServerAdminPassword: "$2a$12$gV6WUTviCkCt1PmxWKjeme893hZ5EFAOvenpMCwwo4kSuBvcHqrAS"

dex:
  env:
    - name: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          key: client-secret
          name: argo-workflows-sso

redisSecretInit:
  enabled: false

server:
  config:
    dex.config: |
      staticClients:
        - id: argo-workflows-sso
          name: Argo Workflow
          redirectURIs:
            - http://127.0.0.1:2746/oauth2/callback
          secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
