#!/usr/bin/env bash

set -e

source /etc/profile

start() {
    yellow; echo "Starting Argo CD..."; normal

    is_first_boot && kustomize_apply /etc/k8sage/core/argo-cd/
    kubectl config set-context --namespace argo-cd --current
    argocd login localhost

    yellow; echo "Waiting for Argo CD deployment..."; normal
    kubectl rollout status --namespace argo-cd deployment argocd-server

    yellow; echo "Forwarding Argo CD port 443..."; normal
    run_in_background kubectl port-forward --namespace argo-cd --address 0.0.0.0 service/argocd-server 443:443 1>/dev/null

    green; echo "Argo CD started."; normal
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then "$1" "${@:2}"; fi
