apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: nginx
  namespace: argo-cd

spec:
  description: nginx project
  sourceRepos:
    - git://k8sage/nginx/
  destinations:
    - namespace: "nginx"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
