apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

helmCharts:
  - name: external-secrets
    namespace: external-secrets
    releaseName: external-secrets
    repo: https://charts.external-secrets.io
    valuesFile: config/values.yaml
    version: 0.17.0

resources:
  - resources/namespace.yaml
