apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-workflows

helmCharts:
  - name: argo-workflows
    namespace: argo-workflows
    releaseName: argo-workflows
    repo: https://argoproj.github.io/argo-helm
    valuesFile: config/values.yaml
    version: 0.45.14

resources:
  - resources/ingress.yaml
  - resources/namespace.yaml
  - secrets/argo-workflows-sso.secret.yaml
