apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: apps-multi-applicationset
  namespace: argo-cd

spec:
  generators:
    - git:
        repoURL: git://host.k3d.internal/applications/
        revision: HEAD
        directories:
          - path: '*/applications/*/overlays/*'
  template:
    metadata:
      name: '{{path[0]}}-{{path[2]}}-{{path[4]}}'
    spec:
      project: apps
      source:
        repoURL: 'git://host.k3d.internal/applications/{{path[0]}}/'
        path: 'applications/{{path[2]}}/overlays/{{path[4]}}'
        targetRevision: HEAD
        plugin:
          name: dry-run-plugin
      destination:
        name: in-cluster
        namespace: '{{path[0]}}-{{path[4]}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
