apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: core-applicationset
  namespace: argo-cd

spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: git://host.k3d.internal/k8sage/
        revision: HEAD
        directories:
          - path: core/*
  template:
    metadata:
      name: "{{index .path.segments 1}}"
    spec:
      project: core
      source:
        repoURL: git://host.k3d.internal/k8sage/
        path: "{{.path.path}}"
        targetRevision: HEAD
      destination:
        name: in-cluster
        namespace: "{{.path.basename}}"
      syncPolicy:
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - PruneLast=true
          - Validate=false
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
