apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-events

helmCharts:
  - name: argo-events
    namespace: argo-events
    releaseName: argo-events
    repo: https://argoproj.github.io/argo-helm
    valuesFile: config/values.yaml
    version: 2.4.15

resources:
  - resources/namespace.yaml
