apiVersion: v1
kind: ConfigMap

metadata:
  name: argocd-rbac-cm

data:
  policy.default: "role:dev"
  policy.csv: |
    p, role:dev, applications, *, */*, allow
    p, role:dev, applications, *, core/*, deny
    p, role:dev, clusters, get, *, allow
    p, role:dev, exec, create, */*, allow
    p, role:dev, logs, get, *, allow
    p, role:dev, projects, *, *, allow
    p, role:dev, repositories, *, *, allow
    p, role:admin, exec, create, */*, allow
