#!/usr/bin/env sh

: ${API_PORT}
: ${HTTPS_PORT}
: ${HTTP_PORT}
: ${K3S_VERSION}
: ${KUBECONFIG}

exec docker run --rm \
    --privileged \
    --name="k8sage-k3s" \
    --network="k8sage" \
    --expose="6443" \
    -p "127.0.0.1:${HTTP_PORT}:80" \
    -p "127.0.0.1:${HTTPS_PORT}:443" \
    -p "127.0.0.1:${API_PORT}:6443" \
    -v /dev/kmsg:/dev/kmsg \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e "K3S_KUBECONFIG_OUTPUT=${KUBECONFIG}" \
    "rancher/k3s:v${K3S_VERSION}-k3s1" \
    server \
    --bind-address="0.0.0.0" \
    --disable="metrics-server" \
    --disable="traefik" \
    --kubelet-arg="eviction-hard=imagefs.available<1%,nodefs.available<1%" \
    --kubelet-arg="eviction-minimum-reclaim=imagefs.available=1%,nodefs.available=1%" \
    --node-name="k8sage-k3s" \
    --snapshotter="native"
