#!/usr/bin/env sh

: ${K3S_VERSION}
: ${KUBECONFIG}

exec docker run --rm --name="k3s" \
    --privileged \
    -v /dev/kmsg:/dev/kmsg:rw \
    -v /var/lib/kubelet:/var/lib/kubelet:rw \
    -p 80:80 \
    -p 443:443 \
    -p 6443:6443 \
    -e "K3S_KUBECONFIG_OUTPUT=${KUBECONFIG}" \
    "rancher/k3s:v${K3S_VERSION}-k3s1" \
    server \
    --bind-address="0.0.0.0" \
    --disable="metrics-server" \
    --disable="traefik" \
    --kubelet-arg="eviction-hard=imagefs.available<1%,nodefs.available<1%" \
    --kubelet-arg="eviction-minimum-reclaim=imagefs.available=1%,nodefs.available=1%" \
    --node-name="k3s" \
    --snapshotter="native"
