apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-cd

helmCharts:
  - name: argo-cd
    namespace: argo-cd
    releaseName: argo-cd
    repo: https://argoproj.github.io/argo-helm
    valuesFile: config/values.yaml
    version: 8.0.1

resources:
  - resources/ingress.yaml
  - resources/namespace.yaml
  - secrets/redis.secret.yaml
  - secrets/repo-creds.secret.yaml
  - components/projects
  - components/applications
  - components/applicationsets
  #  - https://github.com/nedix/argocd-skip-crds-plugin//manifests/resources/?ref=v0.15.0
