- op: add
  path: /data
  value:
    accounts.maintainer: apiKey, login
    accounts.dev: login
    accounts.external: login
    kustomize.buildOptions: --enable-helm
    controller.status.processors: "100"
